[package]
name = "seed-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.9.0", features = ["rustls"] }
actix-ws = "0.3.0"
reqwest = "0.12.7"
sqlx = { version = "0.8.2", features = ["sqlx-postgres", "postgres", "runtime-tokio", "runtime-tokio-rustls"] }
anyhow = { version = "1.0.89", features = ["backtrace", "std"] }
rustls = "0.23.22"
rustls-pemfile = "2.2.0"
base64 = "0.22.1"
flume = "0.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
# hmac = "0.12.1"
# sha2 = "0.10.8"
# hex = "0.4.3"
